#!/usr/local/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use Php74\Command\ClientCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(
   new ClientCommand()
);

$application->run();
